"""
AstroExportStore -- in-memory, time-limited holding area for CSV bytes
generated by Astro AI's export_crm_contacts tool
(app/services/astro_crm_tools.py), served back by GET
/astro-ai/exports/{export_id} (app/api/astro_ai.py).

Mirrors MailboxService's `_pending_states` OAuth-state pattern (same
in-memory dict + TTL + prune-on-access shape -- see
app/services/mailbox_service.py) rather than inventing a new one. Differs
from that precedent in one deliberate way: reading an export does NOT
consume/pop it. Nothing in this feature's requirements calls for
single-use, and a user may reasonably click "Download" more than once
within the TTL window -- so a read here is non-destructive, unlike
MailboxService's single-use `_consume_state()`.

Single-instance constraint (documented, not solved here): this store is
process-local memory, so it only behaves correctly on ONE backend
instance. If Railway is ever scaled to multiple replicas, an export
created on instance A would not be visible to a download request routed
to instance B. Replacing this with shared/distributed storage (e.g. a
database table or object store) is explicitly deferred -- not needed at
today's single-instance deployment.
"""

import uuid
from dataclasses import dataclass, field
from datetime import datetime, timedelta, timezone

EXPORT_TTL = timedelta(minutes=15)


@dataclass
class _PendingExport:
    filename: str
    contact_count: int
    csv_bytes: bytes
    created_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))


class AstroExportStore:
    """Write path: `put()`, called only by the export tool's handler.
    Read path: `get()`, called only by the authenticated download route.
    Never holds anything but the already-generated CSV bytes + display
    metadata -- no filter/query state, no contact objects."""

    def __init__(self):
        self._pending: dict[str, _PendingExport] = {}

    def put(self, filename: str, contact_count: int, csv_bytes: bytes) -> str:
        self._prune_expired()
        export_id = str(uuid.uuid4())
        self._pending[export_id] = _PendingExport(filename=filename, contact_count=contact_count, csv_bytes=csv_bytes)
        return export_id

    def get(self, export_id: str) -> _PendingExport | None:
        self._prune_expired()
        return self._pending.get(export_id)

    def _prune_expired(self) -> None:
        now = datetime.now(timezone.utc)
        expired = [eid for eid, p in self._pending.items() if now - p.created_at > EXPORT_TTL]
        for eid in expired:
            del self._pending[eid]
