"""
Austin Forward -- Sept 10, 2026 Contact Reconciliation (Stage AF-2) -- the
EXPLICIT, frozen, human-reviewed write cohort. This is data, not logic: every
row below was resolved and approved through the Stage AF-1 investigation and
Stage AF-2A dry-run review (conservative email/LinkedIn matching, explicit-
evidence-only Role classification against the live 23-option approved
taxonomy) -- nothing here is computed, scanned, or derived at runtime.

This module intentionally has NO function that discovers additional
candidates and NO store/repository/asyncio import of any kind (verified by
a structural test) -- see app/services/austin_forward_reconciliation.py's
own docstring for why the write path can only ever touch these exact 166
people, forever, until a human explicitly edits this file and a NEW
investigation/review cycle approves the change.

166 unique resolved people = 188 CSV rows - 1 exact duplicate (Alpesh
Kadakia, collapsed to a single row) - 4 name-only candidates - 17
insufficient-identity rows. The 4 name-only and 17 insufficient-identity
rows are DELIBERATELY excluded from this automatic cohort -- manual review
only, never auto-matched or auto-created; they do not appear anywhere in
this file.

EXISTING_CONTACTS (55): already-resolved production Contacts, matched by
exact normalized email and/or LinkedIn URL (0 conflicts). `matched_email_norm`/
`matched_linkedin_norm` are the identity this row was matched on at
investigation time -- compared against the LIVE contact immediately before
any write (see _revalidate_and_prepare()'s drift check), so a row whose
underlying Contact has since changed email/LinkedIn is skipped as drift
rather than trusted blindly.

NEW_CONTACTS (111): people with an email and/or LinkedIn URL that matched no
existing Contact at investigation time -- proposed for creation, re-checked
live immediately before creation (see _revalidate_new_contact()) so a person
who has since been added to the CRM by any other means is skipped rather
than duplicated.

`roles` on every row are ONLY approved, live Role taxonomy values with
explicit Accomplishments-text evidence (Founder/CEO/Investor/CFO/CTO/COO/
CIO/General Partner/Managing Partner/Founding Partner/Managing Director/
Limited Partner/Board Member/Advisor/Lawyer/Doctor/Software Engineer/
Post-Exit Founder). `PEF` is deliberately EXCLUDED from every row (treated
as a relationship/community tag, not an Accomplishments-inferable
professional role, per the approved Stage AF-2 decision) even where the
underlying classifier found "PEF" evidence. `Client`, `Galaxy Member`,
`NOT AN INVESTOR`, `Facilitator`, and `Venture Partner` (not a taxonomy
value) are never inferred from bio text. `role_in_event` (Host/Guest/
Sponsors) is retained on every row for a later, separate Austin Forward
Event History stage -- it is NEVER written to the permanent Contact `role`
field.

`accomplishments` is the full, unedited CSV Accomplishments text for that
person (blank string if the CSV cell was blank) -- preserved verbatim so no
professional/investment intelligence is reduced to structured Role tags
alone; see the reconciliation service's Notes-handling logic for how this
text is inserted/appended without ever overwriting an existing Contact's
Notes.
"""

from dataclasses import dataclass


@dataclass(frozen=True)
class ExistingContactRow:
    crm_contact_id: str
    full_name: str  # report/logging only, never used to (re)match
    matched_email_norm: str | None
    matched_linkedin_norm: str | None
    accomplishments: str
    role_in_event: str  # Host/Guest/Sponsors -- retained for a future Event History stage only
    roles: tuple[str, ...]  # approved Role taxonomy values only, explicit evidence only


@dataclass(frozen=True)
class NewContactRow:
    full_name: str
    first_name: str
    last_name: str
    email: str | None
    linkedin_url: str | None
    accomplishments: str
    role_in_event: str
    roles: tuple[str, ...]


EXISTING_CONTACTS: tuple[ExistingContactRow, ...] = (
    ExistingContactRow(
        crm_contact_id="621eff17-0664-4dfe-8d09-afbe1b408a52",
        full_name="Gary Forni",
        matched_email_norm="gkforni@gmail.com",
        matched_linkedin_norm="linkedin.com/in/garyforni",
        accomplishments="Managing Director at Central Texas Angel Network\nFormer CEO at ListingSpark\nFormer CEO at Tuffwerx, which exited to private equity\nTwo-time exited technology executive",
        role_in_event="Host",
        roles=("CEO", "Managing Director",),
    ),
    ExistingContactRow(
        crm_contact_id="744f81ef-ab19-4c43-8b74-961c5fc688e5",
        full_name="Jeremy Smith",
        matched_email_norm="jersmith22@gmail.com",
        matched_linkedin_norm="linkedin.com/in/jersmith22",
        accomplishments="President at Atempo\nFounded and sold SpotHero to Uber for $600M\nFounded and sold Blockspring to Coinbase\nAcquires and transforms international B2B software companies",
        role_in_event="Host",
        roles=("Founder", "Post-Exit Founder",),
    ),
    ExistingContactRow(
        crm_contact_id="247afbcb-2477-46c6-9c9e-79c9e10e9a05",
        full_name="Jean Anne Booth",
        matched_email_norm="jeananne.booth@gmail.com",
        matched_linkedin_norm="linkedin.com/in/jeanannebooth",
        accomplishments="Founder and CEO of UnaliWear\nFounded Luminary Micro, acquired by Texas Instruments\nFounded Intrinsity, acquired by Apple",
        role_in_event="Host",
        roles=("CEO", "Founder", "Post-Exit Founder",),
    ),
    ExistingContactRow(
        crm_contact_id="a1034d1e-a4c8-488e-a67d-f797f765473e",
        full_name="Connor Tomkies",
        matched_email_norm="connortomkies@gmail.com",
        matched_linkedin_norm="linkedin.com/in/connortomkies",
        accomplishments="Operating Partner at PEF\nOperating Partner at Entrepreneur Cooperative\nFounded and sold SupportNinja to BV Investment Partners\nInvests in and acquires small businesses",
        role_in_event="Host",
        roles=("Founder", "Investor", "Post-Exit Founder",),
    ),
    ExistingContactRow(
        crm_contact_id="998ac243-e9b5-4bf5-83b7-6b645b936f4f",
        full_name="John Constantine",
        matched_email_norm="constantine.johna@gmail.com",
        matched_linkedin_norm="linkedin.com/in/john-constantine-a99824144",
        accomplishments="Early leader and longtime board director at XPEL\nHelped scale XPEL into a publicly traded global automotive-protection company\nFamily-office principal and private investor",
        role_in_event="Host",
        roles=("Board Member", "Investor",),
    ),
    ExistingContactRow(
        crm_contact_id="196cb1c1-fa8d-4b84-90a2-7323c1abac0e",
        full_name="Katelyn Donnelly",
        matched_email_norm="katelyn@avalanche.vc",
        matched_linkedin_norm="linkedin.com/in/katelyndonnelly",
        accomplishments="Co-founded Delivery Associates, sold to private equity\nGeneral Partner at Avalanche\nInvests in early-stage technology companies",
        role_in_event="Host",
        roles=("Founder", "General Partner", "Investor", "Post-Exit Founder",),
    ),
    ExistingContactRow(
        crm_contact_id="c271d560-ceb4-4e8c-8703-b8ec4f7336bf",
        full_name="Dilum Chandrasoma",
        matched_email_norm="dilum12@gmail.com",
        matched_linkedin_norm="linkedin.com/in/dilum-chandrasoma-b5b2b120",
        accomplishments="Family-office principal and private investor\nInvests across real estate and other alternative assets",
        role_in_event="Host",
        roles=("Investor",),
    ),
    ExistingContactRow(
        crm_contact_id="539aa97b-d707-4331-9be0-d33d7a1bb38d",
        full_name="Justin Donald",
        matched_email_norm="justin@lifestyleinvestor.com",
        matched_linkedin_norm="linkedin.com/in/justinwdonald",
        accomplishments="Founder/CEO at The Lifestyle Investor\nPrincipal Owner at MHP Equity Group\nBuilt and exited KC Dawgz\nAuthor and educator focused on cash-flow investing",
        role_in_event="Host",
        roles=("CEO", "Founder",),
    ),
    ExistingContactRow(
        crm_contact_id="477eff98-4b77-4285-8e1e-4ddc98a0d672",
        full_name="Spencer Kaye",
        matched_email_norm="spencer@transform.capital",
        matched_linkedin_norm="linkedin.com/in/spencer-kaye",
        accomplishments="Managing Partner at Transform Capital\nFounded/sold Noble Money to Qenta\nFamily-office principal and private investor",
        role_in_event="Host",
        roles=("Founder", "Investor", "Managing Partner", "Post-Exit Founder",),
    ),
    ExistingContactRow(
        crm_contact_id="acc25702-4f18-42db-935c-6cc85f95a696",
        full_name="Kevin McKeand",
        matched_email_norm="kevin@mutatioventures.com",
        matched_linkedin_norm="linkedin.com/in/kevinmckeand",
        accomplishments="Founding Partner at Mutatio Ventures\nBoard director at Optelos\nEarly investor in FlashParking and Union\nFamily-office principal and private investor",
        role_in_event="Guest",
        roles=("Board Member", "Founding Partner", "Investor",),
    ),
    ExistingContactRow(
        crm_contact_id="659d03b6-46f6-45e4-afe7-6305b83548f8",
        full_name="Scott Kosch",
        matched_email_norm="scott@koschcapital.com",
        matched_linkedin_norm="linkedin.com/in/scottkosch",
        accomplishments="Founded and sold Notification Technologies\nLeads Kosch Capital\nFamily-office principal and private investor",
        role_in_event="Guest",
        roles=("Founder", "Investor", "Post-Exit Founder",),
    ),
    ExistingContactRow(
        crm_contact_id="c248cfe2-73cb-4be8-a916-4c7423438999",
        full_name="Brent Faske",
        matched_email_norm="bfaske@sghmgmt.com",
        matched_linkedin_norm="linkedin.com/in/brent-faske-cpa",
        accomplishments="CFO at SGH Family Office\nMember of the firm's Investment Acquisition Committee\nMore than 25 years of finance and accounting leadership",
        role_in_event="Guest",
        roles=("CFO",),
    ),
    ExistingContactRow(
        crm_contact_id="fa688a9b-8499-4530-966f-98b6c578921a",
        full_name="Dan Kloiber",
        matched_email_norm="dankloiber@gmail.com",
        matched_linkedin_norm="linkedin.com/in/dankloiber",
        accomplishments="Founded Exstream Software and sold it to HP for $772M\nFounded and sold StreamWeaver to Pitney Bowes\nFounded and exited PDR Automated Systems\nFamily-office principal and private investor",
        role_in_event="Guest",
        roles=("Founder", "Investor", "Post-Exit Founder",),
    ),
    ExistingContactRow(
        crm_contact_id="ade8b821-d069-4b6b-9cd5-c53a6011b71c",
        full_name="Hemi Thaker",
        matched_email_norm="hemi@thaker.net",
        matched_linkedin_norm="linkedin.com/in/hemi-thaker-b4891",
        accomplishments="Family-office principal and serial technology entrepreneur\nFounded/sold Anue Systems for $140M, then resold it for $1.6B\nFamily-office principal and private investor",
        role_in_event="Guest",
        roles=("Founder", "Investor", "Post-Exit Founder",),
    ),
    ExistingContactRow(
        crm_contact_id="7e2b5e88-08c9-4af7-b837-7a4637df2480",
        full_name="David Buttross",
        matched_email_norm="david@buttross.com",
        matched_linkedin_norm="linkedin.com/in/david-a-buttross-927b2",
        accomplishments="Family-office principal and private investor\nParticipated in more than $250M of real estate transactions\nAuthor of Long-Term Greedy",
        role_in_event="Guest",
        roles=("Investor",),
    ),
    ExistingContactRow(
        crm_contact_id="ff848802-101a-49c4-81f4-f85fafe7981e",
        full_name="Shravan Parsi",
        matched_email_norm="shravan@americanventures.com",
        matched_linkedin_norm="linkedin.com/in/shravanparsi",
        accomplishments="Founder and CEO of American Ventures\nFamily-office principal and private/institutional investor\nAuthor of The Science of the Deal",
        role_in_event="Guest",
        roles=("CEO", "Founder", "Investor",),
    ),
    ExistingContactRow(
        crm_contact_id="edc1fed9-d331-4a61-87fa-b391490c4ceb",
        full_name="Yotis Tonnelier",
        matched_email_norm="yotis@yxscapital.com",
        matched_linkedin_norm="linkedin.com/in/yotistonnelier",
        accomplishments="Co-founder and Managing Partner at YXS Capital\nTwo-time exited founder\nPreviously advised the family office of HRH Prince N.B.A. Al Saud\nBacked high-growth technology companies across global markets",
        role_in_event="Guest",
        roles=("Founder", "Investor", "Managing Partner", "Post-Exit Founder",),
    ),
    ExistingContactRow(
        crm_contact_id="3c0362d3-a7c7-4d4e-a254-0186bc374472",
        full_name="Roel Peeters",
        matched_email_norm="peeters@gmail.com",
        matched_linkedin_norm="linkedin.com/in/roel-peeters-5b135",
        accomplishments="Founder/CEO at Roost\nSerial entrepreneur with more than 20 years of startup experience\nPreviously built companies across enterprise software, semiconductors and connected-home technology\nFamily-office principal and private investor",
        role_in_event="Guest",
        roles=("CEO", "Founder", "Investor",),
    ),
    ExistingContactRow(
        crm_contact_id="8b4ee125-1fd0-42a5-a714-98c471ec26cd",
        full_name="Ethan Wong",
        matched_email_norm="ethwong@proton.me",
        matched_linkedin_norm="linkedin.com/in/ethan-w-7619a6122",
        accomplishments="Founder/CEO at HiveASMBLD\nFamily-office principal and private investor\nDad co-owns LA Clippers with Steve Ballmer",
        role_in_event="Guest",
        roles=("CEO", "Founder", "Investor",),
    ),
    ExistingContactRow(
        crm_contact_id="4eb4b088-7b2b-4fa4-bf20-f3fa8b62ae2a",
        full_name="Keri Findley",
        matched_email_norm="kanisgarten@gmail.com",
        matched_linkedin_norm="linkedin.com/in/keri-findley-4a974a10a",
        accomplishments="Founder and CEO of Tacora Capital\nBuilt the private-credit firm to approximately $1.6B in regulatory AUM\nRaised an oversubscribed $685M second fund\nLaunched Tacora with a $250M anchor investment from Peter Thiel\nBuilt and led Third Point’s structured-credit business",
        role_in_event="Guest",
        roles=("CEO", "Founder",),
    ),
    ExistingContactRow(
        crm_contact_id="54f0fd47-113b-4ef2-9299-24a0717282a1",
        full_name="Anik Akhund",
        matched_email_norm="anik.akhund@gmail.com",
        matched_linkedin_norm="thefleischerfoundation.org/anik-akhund",
        accomplishments="CEO of Amity Management, a holding company for specialty retail businesses\nFormer co-founder and COO of medical-device distributor OMIE AR",
        role_in_event="Guest",
        roles=("CEO", "COO", "Founder",),
    ),
    ExistingContactRow(
        crm_contact_id="53136c82-9ae1-43b8-8db1-9ca7336127a7",
        full_name="Morgan Flager",
        matched_email_norm="mflager@silvertonpartners.com",
        matched_linkedin_norm="linkedin.com/in/mflager",
        accomplishments="Managing Partner at Silverton Partners\n27+ years of experience as a venture investor and technology executive\nSponsored 26 investments resulting in 13 acquisitions and two IPOs\nRanked No. 6 on Business Insider’s 2023 Seed 100 list of top early-stage investors",
        role_in_event="Guest",
        roles=("Managing Partner",),
    ),
    ExistingContactRow(
        crm_contact_id="348caa6d-6469-4c69-8163-52fa2ce6e3da",
        full_name="Pavan Narra",
        matched_email_norm="pnarra@gmail.com",
        matched_linkedin_norm="linkedin.com/in/pavan-narra-6921b914",
        accomplishments="Interventional and diagnostic radiologist at Ochsner Health\nBoard-certified physician with advanced fellowship training at Emory\nOwner and operator of 25 European Wax Center franchises\nBuilt a substantial multi-state health-and-beauty retail portfolio",
        role_in_event="Guest",
        roles=("Doctor",),
    ),
    ExistingContactRow(
        crm_contact_id="6255e839-925d-4b63-badf-1faa605197bd",
        full_name="Brian Goldberg",
        matched_email_norm="brian@redbudbrands.com",
        matched_linkedin_norm="linkedin.com/in/brian-goldberg-8243a",
        accomplishments="Founder and Executive Chairman at Redbud Brands\nManaging Partner at Astō Consumer Partners, a $350M consumer private equity fund\nLed Amplify Snack Brands through its IPO and $1.7B sale to Hershey\nHelped build Sweet Leaf Tea before its sale to Nestlé; investor/LP in ~50 consumer companies and funds",
        role_in_event="Guest",
        roles=("Founder", "Managing Partner",),
    ),
    ExistingContactRow(
        crm_contact_id="170b9d7c-1ed7-466e-94ac-1cc5bdf348fd",
        full_name="Kenan Hadzi",
        matched_email_norm="kenan@ohayer.com",
        matched_linkedin_norm="linkedin.com/in/kenan-hadziahmetovic-71347a",
        accomplishments="Private investor across venture capital, private equity, real estate, and public markets\nPrincipal and sole owner of CapLab, spanning technology, real estate, retail, and research\nManages Matt O'Hayer's family office",
        role_in_event="Guest",
        roles=("Investor",),
    ),
    ExistingContactRow(
        crm_contact_id="df7dbbc3-85d3-4820-9089-7efb4ddb06fa",
        full_name="Jim Curry",
        matched_email_norm="jim@topwater.ai",
        matched_linkedin_norm="linkedin.com/in/jimncurry",
        accomplishments="Co-founder and CEO of BuildGroup, an operator-led software investment firm\nHelped scale Rackspace into a $1.5B cloud leader\nCo-founded OpenStack, the leading open-source cloud computing project\nAlso co-founded Topwater and Vatra Group, supporting Ukrainian technology and defense innovation",
        role_in_event="Guest",
        roles=("CEO", "Founder",),
    ),
    ExistingContactRow(
        crm_contact_id="36fb1f6d-f7be-426b-bf71-240b70114b82",
        full_name="Venu Shampant",
        matched_email_norm="venu@liveoakvp.com",
        matched_linkedin_norm="linkedin.com/in/venu-shamapant-7987007",
        accomplishments="Founding Partner at LiveOak Ventures\nFormer GP at Austin Ventures",
        role_in_event="Guest",
        roles=("Founding Partner",),
    ),
    ExistingContactRow(
        crm_contact_id="a874f341-c0d7-4275-8142-b83dd088cf18",
        full_name="Emma Cartmell",
        matched_email_norm="emma@createhealth.vc",
        matched_linkedin_norm="linkedin.com/in/ecartmell",
        accomplishments="Managing Partner at Create Health Ventures\nEarly-stage investor at Cartmell Ventures\nFamily-office principal and private investor",
        role_in_event="Guest",
        roles=("Investor", "Managing Partner",),
    ),
    ExistingContactRow(
        crm_contact_id="ff7dcd40-b699-420d-8cfb-c51c9b328d0d",
        full_name="Ricky Joshi",
        matched_email_norm="rickyjoshi01@gmail.com",
        matched_linkedin_norm="linkedin.com/in/rickyjoshi",
        accomplishments="Co-founder and advisor at Saatva\nBuilt its marketing infrastructure and helped scale the luxury mattress brand beyond $400M in annual revenue\nLed Saatva’s national retail rollout and product expansion\nPartner and investment committee member at Springdale Ventures",
        role_in_event="Guest",
        roles=("Advisor", "Founder",),
    ),
    ExistingContactRow(
        crm_contact_id="d93456cf-c412-423e-974c-b4a5d04fa913",
        full_name="Dana Loberg",
        matched_email_norm="dana.loberg@gmail.com",
        matched_linkedin_norm=None,
        accomplishments="2x exited founder\nFounded/sold MovieLaLa to Snapchat\nCEO at Leo AR",
        role_in_event="Guest",
        roles=("CEO", "Founder", "Post-Exit Founder",),
    ),
    ExistingContactRow(
        crm_contact_id="64bb0f38-06e8-46d6-8416-1da2f5faee00",
        full_name="Ray Wolf",
        matched_email_norm="ray.wolf@televerohealth.com",
        matched_linkedin_norm="linkedin.com/in/raymondwolf",
        accomplishments="CEO at Televero Health\nEntrepreneurial Advisory Board at Culturati: Summit",
        role_in_event="Guest",
        roles=("Advisor", "CEO",),
    ),
    ExistingContactRow(
        crm_contact_id="adca3b8f-22dd-40d9-9307-a7ba11c771cb",
        full_name="Jeff Swearingen",
        matched_email_norm="jtswearingen@gmail.com",
        matched_linkedin_norm="linkedin.com/in/jeffswearingen",
        accomplishments="Founded/sold SecureLink to Imprivata for $600M+\nFamily-office principal and private investor",
        role_in_event="Guest",
        roles=("Founder", "Investor", "Post-Exit Founder",),
    ),
    ExistingContactRow(
        crm_contact_id="4536954e-e1af-4aee-a4fe-4296ba11bb97",
        full_name="Joe Kim",
        matched_email_norm="0.joekim.1@gmail.com",
        matched_linkedin_norm="linkedin.com/in/josephkimprofile",
        accomplishments="CEO at Druid AI\nFormer CEO at Sumo Logic\nFormer CTO at HP\nFormer CTO at Citrix\nBoard of Director at SmartBear",
        role_in_event="Guest",
        roles=("CEO", "CTO",),
    ),
    ExistingContactRow(
        crm_contact_id="1beb011b-c870-48e5-8697-d4000e00f5d6",
        full_name="Mary Mandel",
        matched_email_norm="marymandel@yahoo.com",
        matched_linkedin_norm=None,
        accomplishments="2x exited founder\nFounder of Olympus Development Partners and Olympus Foundation\nCo-Founder at Sanctuary\nFamily-office principal and private investor",
        role_in_event="Guest",
        roles=("Founder", "Investor", "Post-Exit Founder",),
    ),
    ExistingContactRow(
        crm_contact_id="8bd11c66-4a60-4af4-ac71-b31a99cb22a4",
        full_name="Ed Sattar",
        matched_email_norm="ed.sattar@edtechventures.io",
        matched_linkedin_norm="linkedin.com/in/edsattar",
        accomplishments="Founder & Managing Director at Edtech Ventures\nChairman & Investor at EnableU\nForbes Business Council Member",
        role_in_event="Guest",
        roles=("Founder", "Managing Director",),
    ),
    ExistingContactRow(
        crm_contact_id="edb039ab-dc52-4c64-aacb-48749e296560",
        full_name="Cooper Hefner",
        matched_email_norm="cooper@hefnercap.com",
        matched_linkedin_norm="linkedin.com/in/cooper-hefner-7b4b32159",
        accomplishments="Managing Partner at Hefner Capital and family-office investor\nFormer Chief Creative Officer and Head of Global Partnerships at Playboy Enterprises\nLed a $100M investor bid to acquire the Playboy brand\nU.S. Air Force reservist and Forbes 30 Under 30 honoree",
        role_in_event="Guest",
        roles=("Managing Partner",),
    ),
    ExistingContactRow(
        crm_contact_id="363a77d7-59dc-4865-baaa-255dc7114744",
        full_name="Darin Brannan",
        matched_email_norm="darinbrannan@gmail.com",
        matched_linkedin_norm="linkedin.com/in/darinbrannan",
        accomplishments="CEO at Terminal Industries\nCEO Partner at Tritium Partners\nExecutive Advisor at Blue Sea Capital LLC",
        role_in_event="Guest",
        roles=("Advisor", "CEO",),
    ),
    ExistingContactRow(
        crm_contact_id="118a19f9-500f-41ce-bf85-13f0ee4f7fc3",
        full_name="Christophe Ponsart",
        matched_email_norm="cponsart@gmail.com",
        matched_linkedin_norm="linkedin.com/in/christopheponsart",
        accomplishments="Founder of ContextFit, an open-source AI memory system\nCo-founded OnPrem Solution Partners, which sold a majority stake to Qvest in 2020\nHelped build OnPrem into a 250-person media technology consultancy\nPrivate Investor",
        role_in_event="Guest",
        roles=("Founder", "Investor", "Post-Exit Founder",),
    ),
    ExistingContactRow(
        crm_contact_id="30729143-1dc9-4db3-b81b-299ed90e4ae5",
        full_name="Mason Stephens",
        matched_email_norm="mstephens@validiti.com",
        matched_linkedin_norm="linkedin.com/in/mason-stephens-29abbb239",
        accomplishments="Cofounder at Validiti\nStrategic Advisor at Visionary Fiber Technologies\nFormer COO at HG Partners\nGrandson of Jack Stephens (family office)",
        role_in_event="Guest",
        roles=("Advisor", "COO", "Founder",),
    ),
    ExistingContactRow(
        crm_contact_id="c8eac582-4d96-47c5-8581-d31a7d672f6d",
        full_name="Rajul Kadakia",
        matched_email_norm="rajulk@gmail.com",
        matched_linkedin_norm="linkedin.com/in/rajulk",
        accomplishments="Cofounder and Chairwoman at Ayana\nBoard Member at McCombs Center for Global Business\nFamily-office principal and private investor",
        role_in_event="Guest",
        roles=("Board Member", "Founder", "Investor",),
    ),
    ExistingContactRow(
        crm_contact_id="527efe1f-455c-41ab-9d35-cd35e6e659ba",
        full_name="Alpesh Kadakia",
        matched_email_norm="alpeshk@gmail.com",
        matched_linkedin_norm="linkedin.com/in/alpeshkadakia",
        accomplishments="Founder at Postlane\nPresident at K2 Capital\nFamily-office principal and private investor",
        role_in_event="Guest",
        roles=("Founder", "Investor",),
    ),
    ExistingContactRow(
        crm_contact_id="a7f2129d-fc36-4a85-8f78-c788923c531b",
        full_name="Oksana Malysheva",
        matched_email_norm="oksana@sputnikatx.com",
        matched_linkedin_norm="linkedin.com/in/oksana-malysheva-%f0%9f%87%ba%f0%9f%87%a6-62193a3",
        accomplishments="Founder at Sputnik ATX VC\nBuilt an early-stage portfolio of more than 70 companies, with a majority led by women or minorities\nNamed to Forbes’ 50 Over 50 list for her impact in investing\nPh.D. physicist and former McKinsey consultant who helped market Motorola’s RAZR",
        role_in_event="Guest",
        roles=("Founder",),
    ),
    ExistingContactRow(
        crm_contact_id="972d099f-ebc1-4f41-aba2-6cdf5c335766",
        full_name="Michele Skelding",
        matched_email_norm="micheleskelding@gmail.com",
        matched_linkedin_norm="linkedin.com/in/micheleskelding",
        accomplishments="Founder and principal at Capital Sage Ventures\nTIGER 21 Chair\nFormer SVP of Technology and Innovation at the Austin Chamber of Commerce",
        role_in_event="Guest",
        roles=("Founder",),
    ),
    ExistingContactRow(
        crm_contact_id="371c0a13-df8a-4fc1-a132-04b5f80e0a15",
        full_name="Gustavo Artaza",
        matched_email_norm="gustavoartaza4@gmail.com",
        matched_linkedin_norm="linkedin.com/in/gustavo-artaza-9348279",
        accomplishments="Founded ISA, a global study-abroad provider\nGrew it to 700+ universities and 6,000 students annually before its 2015 private-equity acquisition\nManaging Director of Alma Tierra Ventures, investing in and managing real estate\nFounded Gen1 Research; invests in MedTech",
        role_in_event="Guest",
        roles=("Founder", "Investor", "Managing Director",),
    ),
    ExistingContactRow(
        crm_contact_id="619b79d1-2b07-43e1-9808-0096308f8ffe",
        full_name="Joseph Liu",
        matched_email_norm="ecomliu@gmail.com",
        matched_linkedin_norm="linkedin.com/in/investorjoseph",
        accomplishments="Angel investor and Central Texas Angel Network member since 2015\nVenture Partner at Wise Ocean\nMentors early-stage founders through CTAN, Founder Institute, and SKU\nParticipates in startup diligence, investment discussions, and Austin’s entrepreneurial ecosystem",
        role_in_event="Guest",
        roles=("Founder", "Investor",),
    ),
    ExistingContactRow(
        crm_contact_id="6050d603-c257-45c8-8ada-0dc39938e866",
        full_name="Chris Petkas",
        matched_email_norm="chris@ctcapital.vc",
        matched_linkedin_norm="linkedin.com/in/chris-petkas",
        accomplishments="General Partner at Contrarian Thinking Capital, an early-stage VC and Main Street investment firm\nFormer U.S. Navy SEAL who served for 10 years\nFormer Defense Innovation Unit AI leader and national-security advisor\nInvests in companies including Figure AI, Saronic, SkyFi, and Cents",
        role_in_event="Guest",
        roles=("Advisor", "General Partner", "Investor",),
    ),
    ExistingContactRow(
        crm_contact_id="ecb1cc60-ec66-4d9b-af68-59454a729b92",
        full_name="Dave Maloney",
        matched_email_norm="dave@orchestramacro.com",
        matched_linkedin_norm="linkedin.com/in/sixstar",
        accomplishments="Serial entrepreneur and two-time post-exit founder\nFounded The D10, raising $15M+ for pediatric cancer through nationally televised athletic events\nFounded Orchestra Macrosystems, a defense-software company serving the U.S. Air Force\nFormer Morgan Stanley professional and All-SEC Academic student-athlete",
        role_in_event="Guest",
        roles=("Founder", "Post-Exit Founder",),
    ),
    ExistingContactRow(
        crm_contact_id="5565e3d1-3bf5-4f09-8d28-abbfb2d7d39b",
        full_name="Mike Boyle",
        matched_email_norm="mike@spacecowboyventures.com",
        matched_linkedin_norm="linkedin.com/in/michaelbboyle",
        accomplishments="Co-founder and Senior Advisor at Sempulse; former CEO of AppBus\nFormer CIO of Aflac and CIO/COO of Allstate Financial\nManaged $65M early-stage fund at Ecliptic Capital, investing in 18 deep-science companies\nFour-time founder with multiple startup and private-equity exits",
        role_in_event="Guest",
        roles=("Advisor", "CEO", "CIO", "COO", "Founder", "Investor", "Post-Exit Founder",),
    ),
    ExistingContactRow(
        crm_contact_id="6f156efa-dcd3-4337-9fa1-3db97546ff09",
        full_name="Sahil Diwan",
        matched_email_norm="sahil@sentienthome.ai",
        matched_linkedin_norm="linkedin.com/in/sahil-diwan",
        accomplishments="Former Siemens VP\nFamily-office principal and private investor",
        role_in_event="Guest",
        roles=("Investor",),
    ),
    ExistingContactRow(
        crm_contact_id="65aea36e-ed52-4cec-a508-b85690f3acb1",
        full_name="Caroline Boudreaux",
        matched_email_norm="caroline@miraclefoundation.org",
        matched_linkedin_norm="linkedin.com/in/carolineboudreaux",
        accomplishments="Founder of Miracle Foundation, transforming orphan and foster-care systems worldwide\nOrganization has directly supported 40,000+ children and aims to eliminate orphanages by 2040\nWorld Economic Forum Young Global Leader and UBS Global Visionary\nRecipient of the United Nations Humanitarian Award",
        role_in_event="Guest",
        roles=("Founder",),
    ),
    ExistingContactRow(
        crm_contact_id="67ed2793-158f-400d-bdd9-61442b931241",
        full_name="Bryton Shang",
        matched_email_norm="bryton.shang@gmail.com",
        matched_linkedin_norm="linkedin.com/in/brytonshang",
        accomplishments="Founded Aquabyte, applying AI and robotics to improve global aquaculture\nLed the company through a multi-hundred-million-dollar acquisition\nFounded the U.S. Commerce Department’s National AI Center and advised NOAA\nForbes 30 Under 30; graduated first in his Princeton engineering class",
        role_in_event="Guest",
        roles=("Founder",),
    ),
    ExistingContactRow(
        crm_contact_id="48a10c07-2890-4051-8880-79f60431443b",
        full_name="Amanda Bradford",
        matched_email_norm="amanda.bradford@gmail.com",
        matched_linkedin_norm="linkedin.com/in/amandabradford",
        accomplishments="Founded and sold The League to Match.com\nFamily-office principal and private investor",
        role_in_event="Guest",
        roles=("Founder", "Investor", "Post-Exit Founder",),
    ),
    ExistingContactRow(
        crm_contact_id="8bd8aa10-876f-4770-a54c-7d6040b705e6",
        full_name="Boris Portman",
        matched_email_norm="boris@betterengineer.com",
        matched_linkedin_norm="linkedin.com/in/borisportman",
        accomplishments="Founder and CEO of BetterEngineer, connecting companies with senior Latin American engineers\nFounder of Salsa Ventures, investing in technology startups and real estate\nFormer VP of Engineering and multi-company CTO\nTechstars mentor and Carnegie Mellon software-engineering advisory board member",
        role_in_event="Guest",
        roles=("Advisor", "Board Member", "CEO", "CTO", "Founder",),
    ),
    ExistingContactRow(
        crm_contact_id="e2b78f55-af18-4f67-9edc-796c61ba8723",
        full_name="Jay Lamy",
        matched_email_norm="lamy@aquilacommercial.com",
        matched_linkedin_norm="linkedin.com/in/jay-lamy",
        accomplishments="",
        role_in_event="Guest",
        roles=(),
    ),
    ExistingContactRow(
        crm_contact_id="7b9a52c8-c124-4cdc-964b-23b6a5c2624e",
        full_name="Matt Reibling",
        matched_email_norm="matt@techsyn.us",
        matched_linkedin_norm="linkedin.com/in/mgreibling",
        accomplishments="Techsyn Ventures",
        role_in_event="Sponsors",
        roles=(),
    ),
)

NEW_CONTACTS: tuple[NewContactRow, ...] = (
    NewContactRow(
        full_name="Joe Liemandt",
        first_name="Joe",
        last_name="Liemandt",
        email="liemandt@trilogy.com",
        linkedin_url="https://www.linkedin.com/in/liemandt/",
        accomplishments="Founder/Principal at Alpha School\nFounded Trilogy Software and ESW Capital\nBuilt Trilogy into a billion-dollar enterprise software company\nYoungest self-made member of the Forbes 400 in 1996\nFamily-office principal and private investor",
        role_in_event="Host",
        roles=("Founder", "Investor",),
    ),
    NewContactRow(
        full_name="Eliot Gattegno",
        first_name="Eliot",
        last_name="Gattegno",
        email="eliot.gattegno@alpha.school",
        linkedin_url="https://www.linkedin.com/in/eliotgattegno/",
        accomplishments="Head of Ecosystem at Alpha School\nAuthor of BELONG, focused on communities that transform education\nFormer clinical professor at NYU Shanghai\nFounded CUHK Shenzhen’s Center for Innovation, Design, and Entrepreneurship",
        role_in_event="Host",
        roles=("Founder",),
    ),
    NewContactRow(
        full_name="Tanuj Gulati",
        first_name="Tanuj",
        last_name="Gulati",
        email="tanujgulati06@gmail.com",
        linkedin_url="https://www.linkedin.com/in/tanujgulati/",
        accomplishments="Founder/sold Securonix to Vista Equity Partners\nBuilt Securonix into a multibillion-dollar cybersecurity company\nFamily-office principal and private investor",
        role_in_event="Host",
        roles=("Founder", "Investor", "Post-Exit Founder",),
    ),
    NewContactRow(
        full_name="Bridget Ramey",
        first_name="Bridget",
        last_name="Ramey",
        email="bridgetramey@me.com",
        linkedin_url="https://www.linkedin.com/in/bridgetramey/",
        accomplishments="Luxury real estate advisor at Sotheby's International Realty\nTexas' top luxury residential realtor\nRepresents prominent clients and landmark Austin properties",
        role_in_event="Host",
        roles=("Advisor",),
    ),
    NewContactRow(
        full_name="Chris Beaman",
        first_name="Chris",
        last_name="Beaman",
        email="chris@astronomic.com",
        linkedin_url="https://www.linkedin.com/in/chrisbeaman/",
        accomplishments="CEO at Brokk\nFounded and sold MyPostOpCare to private equity\nFounded and sold Grapevine to Ideanomics\nTwo-time exited technology founder",
        role_in_event="Host",
        roles=("CEO", "Founder", "Post-Exit Founder",),
    ),
    NewContactRow(
        full_name="Grant Butler",
        first_name="Grant",
        last_name="Butler",
        email="grant@butlerinvesting.com",
        linkedin_url="https://www.linkedin.com/in/grantebutler/",
        accomplishments="Principal of the Butler Family Office\nInvests across private equity, venture capital and real estate\nAustin-based private-markets and family-office professional",
        role_in_event="Guest",
        roles=("Investor",),
    ),
    NewContactRow(
        full_name="Jason Freedman",
        first_name="Jason",
        last_name="Freedman",
        email="jason@orangecollective.vc",
        linkedin_url="https://www.linkedin.com/in/jasonfreedman/",
        accomplishments="General Partner at Orange Collective\nFounded 42Floors, acquired by JLL in 2018\nFounded FlightCaster, acquired by Next Jump in 2010\nTwo-time Y Combinator founder",
        role_in_event="Guest",
        roles=("Founder", "General Partner", "Post-Exit Founder",),
    ),
    NewContactRow(
        full_name="Igor Vainshtein",
        first_name="Igor",
        last_name="Vainshtein",
        email="me@igorvainshtein.com",
        linkedin_url="https://www.linkedin.com/in/igorvainshtein/",
        accomplishments="Founded 24/7 Golf and sold it to GOLFTEC\nCreated GolfTrak.app\nSerial entrepreneur, inventor and business author",
        role_in_event="Guest",
        roles=("Founder", "Post-Exit Founder",),
    ),
    NewContactRow(
        full_name="Vaibhav Nivargi",
        first_name="Vaibhav",
        last_name="Nivargi",
        email="vaibhav@moveworks.com",
        linkedin_url="https://www.linkedin.com/in/vnivargi/",
        accomplishments="Founder/CTO at Moveworks\nFounded ClearStory Data, acquired by Alteryx\nEarly engineer at Aster Data, acquired by Teradata",
        role_in_event="Guest",
        roles=("CTO", "Founder", "Post-Exit Founder",),
    ),
    NewContactRow(
        full_name="Peter Wang",
        first_name="Peter",
        last_name="Wang",
        email="misterwang@gmail.com",
        linkedin_url="https://www.linkedin.com/in/pzwang/",
        accomplishments="Founder and Chief AI Officer at Anaconda ($150M/yr)\nPrivate investor in early-stage startups",
        role_in_event="Guest",
        roles=("Founder", "Investor",),
    ),
    NewContactRow(
        full_name="Betsy Buttross",
        first_name="Betsy",
        last_name="Buttross",
        email=None,
        linkedin_url="https://www.linkedin.com/in/betsyfreemanbuttross/",
        accomplishments="Austin-based real estate broker specializing in residential and luxury properties\nExperienced in serving buyers and sellers across the Austin market\nWife of family-office principal and private investor David Buttross\nConnected to a family with longstanding real estate investment interests",
        role_in_event="Guest",
        roles=("Investor",),
    ),
    NewContactRow(
        full_name="Peter Barlin",
        first_name="Peter",
        last_name="Barlin",
        email=None,
        linkedin_url="https://www.linkedin.com/in/peter-barlin-36953a188/",
        accomplishments="Longtime Austin real estate developer focused on adaptive-reuse and mixed-use properties\nCo-developer of Crestview Village, a transit-oriented mixed-use project\nSold a three-property East Austin creative-office portfolio to CIM Group\nOwns/develops properties housing FloSports, Cosmic Coffee, retail, restaurant, and wellness concepts",
        role_in_event="Guest",
        roles=(),
    ),
    NewContactRow(
        full_name="Josh Meyer",
        first_name="Josh",
        last_name="Meyer",
        email="josh@jlmfinancialinvestments.com",
        linkedin_url="https://www.linkedin.com/in/joshualmeyer/",
        accomplishments="Managing Partner at JLM Financial Partners\nLeads capital raising and investment oversight across U.S. and Asian portfolio companies\nCo-founded JLM Living, developing build-to-rent communities across the Southeast and Southwest\nHelped exit United PF Partners, a 168-location Planet Fitness franchisee",
        role_in_event="Guest",
        roles=("Founder", "Managing Partner",),
    ),
    NewContactRow(
        full_name="Itay Vinik",
        first_name="Itay",
        last_name="Vinik",
        email="itay@equi.com",
        linkedin_url="https://www.linkedin.com/in/itayvinik/",
        accomplishments="Founder and Chief Investment Officer at Equi\nMore than 15 years in asset management",
        role_in_event="Guest",
        roles=("Founder",),
    ),
    NewContactRow(
        full_name="Raj Gokal",
        first_name="Raj",
        last_name="Gokal",
        email="raj@solana.com",
        linkedin_url="https://www.linkedin.com/in/rajgokal/",
        accomplishments="Founder at Solana ($44B market cap)\nHelped build one of the world's largest blockchain ecosystems\nFamily-office principal and private investor",
        role_in_event="Guest",
        roles=("Founder", "Investor",),
    ),
    NewContactRow(
        full_name="Rob Aird",
        first_name="Rob",
        last_name="Aird",
        email="aird.robert@gmail.com",
        linkedin_url="https://www.linkedin.com/in/robert-aird-82bab69/",
        accomplishments="Family-office principal and private investor\nEarly leadership at Virtu Financial (IPO)\nActive in civic and community leadership",
        role_in_event="Guest",
        roles=("Investor",),
    ),
    NewContactRow(
        full_name="Chris Milam",
        first_name="Chris",
        last_name="Milam",
        email="cmilam@idmco.us",
        linkedin_url="https://www.linkedin.com/in/cfmilam/",
        accomplishments="Founder and owner of International Development Management (IDM)\nDeveloper behind the Hill Country Galleria and Shops at the Galleria\nFour decades of experience in commercial real estate and technology ventures\nFounded businesses spanning urban development, transportation, and emerging technologies",
        role_in_event="Guest",
        roles=("Founder",),
    ),
    NewContactRow(
        full_name="Sonia Milam",
        first_name="Sonia",
        last_name="Milam",
        email=None,
        linkedin_url="https://www.linkedin.com/in/sonia-milam-27b549301/",
        accomplishments="CEO of White Rocks Entertainment\nLeading development of the 71-acre UMusic Hotel & Private Residences Austin\nProject includes a 150-room hotel, 600 residences, and 10,000-seat amphitheater\nSupporting an endowment expected to provide $10M annually for Austin nonprofits",
        role_in_event="Guest",
        roles=("CEO",),
    ),
    NewContactRow(
        full_name="Eduardo Maldonado",
        first_name="Eduardo",
        last_name="Maldonado",
        email="bossracecar@yahoo.com",
        linkedin_url="https://www.linkedin.com/in/eduardomaldonadov/",
        accomplishments="COO and Co-Founder of EquityX, an operator-led business acquisition platform\nFounded and sold GDX Travel to Hopper\nCo-founded Undertrail, a multimodal online travel platform for Latin America\nOperator and private investor focused on business ownership and long-term value creation",
        role_in_event="Guest",
        roles=("COO", "Founder", "Investor", "Post-Exit Founder",),
    ),
    NewContactRow(
        full_name="Will Ashcroft",
        first_name="Will",
        last_name="Ashcroft",
        email="willa@cingoglobal.com",
        linkedin_url=None,
        accomplishments="Serial entrepreneur and founder of private aviation membership company Jumpjet\nFounded the World Rugby Club Championships and established multiple air-medicine companies\nFormer co-owner of the VIP helicopter concession at Atlantis Paradise Island",
        role_in_event="Guest",
        roles=("Founder",),
    ),
    NewContactRow(
        full_name="Vinny Lingham",
        first_name="Vinny",
        last_name="Lingham",
        email=None,
        linkedin_url="https://www.linkedin.com/in/vinnylingham/",
        accomplishments="Co-founder and chairman of Civic and founder of Rumi\nFounded and sold Gyft to First Data for a reported $54M\nFounded Incubeta, later acquired by Carlyle\nFormer Multicoin Capital general partner and early investor in Solana, Filecoin, and Render",
        role_in_event="Guest",
        roles=("Founder", "General Partner", "Post-Exit Founder",),
    ),
    NewContactRow(
        full_name="Kavin Lingham",
        first_name="Kavin",
        last_name="Lingham",
        email=None,
        linkedin_url="linkedin.com/in/kavinlinghamskyshield/?skipRedirect=true",
        accomplishments="Founder and CEO of Sovereign ATX, deploying private on-premise AI infrastructure\nBuilding Relay, a 5G platform for underserved communities",
        role_in_event="Guest",
        roles=("CEO", "Founder",),
    ),
    NewContactRow(
        full_name="Aater Suleman",
        first_name="Aater",
        last_name="Suleman",
        email="aater@vixul.com",
        linkedin_url="https://www.linkedin.com/in/aatersuleman/",
        accomplishments="Co-founded and led Flux7, acquired by NTT DATA\nUniversity of Texas at Austin faculty member\nFamily-office principal and private investor",
        role_in_event="Guest",
        roles=("Founder", "Investor", "Post-Exit Founder",),
    ),
    NewContactRow(
        full_name="Mike (Lucky) Wilson",
        first_name="Mike (Lucky)",
        last_name="Wilson",
        email="mike@goneoffdeep.com",
        linkedin_url="https://www.linkedin.com/in/luckymikewilson",
        accomplishments="Founded and sold multiple video-game publishing companies\nFamily-office principal and private investor",
        role_in_event="Guest",
        roles=("Founder", "Investor", "Post-Exit Founder",),
    ),
    NewContactRow(
        full_name="Jay Bourgana",
        first_name="Jay",
        last_name="Bourgana",
        email="jaybourgana@gmail.com",
        linkedin_url="https://www.linkedin.com/in/jay-bourgana/",
        accomplishments="Founder of Acquisition Collective\nFounded/sold Homearly for $350M\nFamily-office principal and private investor",
        role_in_event="Guest",
        roles=("Founder", "Investor", "Post-Exit Founder",),
    ),
    NewContactRow(
        full_name="Jeremy Baker",
        first_name="Jeremy",
        last_name="Baker",
        email="jhubert@gmail.com",
        linkedin_url="https://www.linkedin.com/in/jhubert/",
        accomplishments="Founder/CTO at Zipline\nFounded/sold MightyHive by S4 Capital for $150M+\nFamily-office principal and private investor",
        role_in_event="Guest",
        roles=("CTO", "Founder", "Investor", "Post-Exit Founder",),
    ),
    NewContactRow(
        full_name="Katherine Morris",
        first_name="Katherine",
        last_name="Morris",
        email="katherine.morris@favordelivery.com",
        linkedin_url="https://www.linkedin.com/in/katherine-morris1/",
        accomplishments="Account Executive for Favor Delivery and H-E-B’s Central Austin territory\nBoard member and Chair of Orchestra Relations at Austin Symphony Orchestra\nCombines corporate partnerships expertise with leadership in Austin’s arts community",
        role_in_event="Guest",
        roles=("Board Member",),
    ),
    NewContactRow(
        full_name="Jonathan Ellis",
        first_name="Jonathan",
        last_name="Ellis",
        email="jbellis@gmail.com",
        linkedin_url="https://www.linkedin.com/in/jbellis/",
        accomplishments="Founder at Brokk\nFounded/sold DataStax to IBM for $700M+\nApache Cassandra creator",
        role_in_event="Guest",
        roles=("Founder", "Post-Exit Founder",),
    ),
    NewContactRow(
        full_name="Karthik Koduru",
        first_name="Karthik",
        last_name="Koduru",
        email="karthik@spsk.vc",
        linkedin_url="https://www.linkedin.com/in/kkoduru/",
        accomplishments="Founder and CEO of Archer Review\nBoard-certified oncologist and health-tech entrepreneur\nScaled Archer Review to No. 46 on the 2024 Inc. 5000\nThree-time Inc. 5000 honoree and 2024–2025 EY Entrepreneur Of The Year Southwest finalist\nCo-founded healthcare platforms OncoPower and PulsedIn",
        role_in_event="Guest",
        roles=("CEO", "Doctor", "Founder",),
    ),
    NewContactRow(
        full_name="Jeff Cardenas",
        first_name="Jeff",
        last_name="Cardenas",
        email="jeff.cardenas@gmail.com",
        linkedin_url="https://www.linkedin.com/in/jeffrey-cardenas/",
        accomplishments="Co-founder and CEO of Apptronik\nBuilt the humanoid-robotics company to an approximately $5B valuation\nRaised $520M from investors including Google, Mercedes-Benz and QIA\nDeveloped Apollo from robotics work originating with NASA and UT Austin",
        role_in_event="Guest",
        roles=("CEO", "Founder",),
    ),
    NewContactRow(
        full_name="Christy Cardenas",
        first_name="Christy",
        last_name="Cardenas",
        email="cc@irisinvest.io",
        linkedin_url="https://www.linkedin.com/in/christy-cardenas/",
        accomplishments="Founder and CEO of Iris, an intelligence and investment company\nMore than 15 years of institutional investment and fundraising experience\nManaged or advised approximately $15B across VC, private equity and investment banking\nFormer Managing Partner at Grit Ventures and early Apptronik investor\nInvests across AI, robotics, energy, power and space",
        role_in_event="Guest",
        roles=("CEO", "Founder", "Investor", "Managing Partner",),
    ),
    NewContactRow(
        full_name="Diana Gaspar",
        first_name="Diana",
        last_name="Gaspar",
        email=None,
        linkedin_url="https://www.linkedin.com/in/diana-gaspar-a9186122/",
        accomplishments="Part of Capital Commercial Investments and Dragonfly Family Office\nWorks within a family-owned investment platform managing approximately $1.9B across nearly 13M square feet\nThe platform has completed more than 200 commercial real estate deals",
        role_in_event="Guest",
        roles=(),
    ),
    NewContactRow(
        full_name="Jag Bath",
        first_name="Jag",
        last_name="Bath",
        email="jagbath@gmail.com",
        linkedin_url="https://www.linkedin.com/in/jag-bath/",
        accomplishments="Four-time startup executive and CEO with four consecutive exits—three acquisitions and one IPO\nLed Favor as CEO through its acquisition by H-E-B\nServed concurrently as H-E-B’s Chief Digital Officer, overseeing its digital products and services\nCompany advisor, board member, and angel investor in disruptive technology businesses",
        role_in_event="Guest",
        roles=("Advisor", "Board Member", "CEO", "Investor",),
    ),
    NewContactRow(
        full_name="Blake Lieberman",
        first_name="Blake",
        last_name="Lieberman",
        email="blakelieberman1@gmail.com",
        linkedin_url="https://www.linkedin.com/in/blake-lieberman",
        accomplishments="Founder of 021, an Austin-based hardware investment initiative\nDeploying $1M to support founders building on a 540-acre development campus\nCo-founded the $8.5M pre-seed and seed-stage Rief Ventures fund\nEarly-stage investor focused on hardware and technology companies",
        role_in_event="Guest",
        roles=("Founder",),
    ),
    NewContactRow(
        full_name="Arun Prakash",
        first_name="Arun",
        last_name="Prakash",
        email="arun@carbonarrow.co",
        linkedin_url="https://www.linkedin.com/in/arunprakash1",
        accomplishments="Founder and Managing Director of Carbon Arrow\nFormer CFO of The Boring Company and enterprise AI company Cerebri AI\nCo-founded and sold flying-car company Terrafugia to Geely Holdings\nFormer Virgo Capital partner who led technology acquisitions, exits, and portfolio operations",
        role_in_event="Guest",
        roles=("CFO", "Founder", "Managing Director", "Post-Exit Founder",),
    ),
    NewContactRow(
        full_name="John Maseredjian",
        first_name="John",
        last_name="Maseredjian",
        email="johnny@inkind.com",
        linkedin_url="https://www.linkedin.com/in/maser/",
        accomplishments="SVP of Sales, Business Development, and Partnerships at inKind\nHelped scale inKind to 8,500+ funded restaurants and five million+ guests\nPart of the leadership team behind more than $760M in deployed restaurant capital\nFormer Vice President at JohnHart Real Estate",
        role_in_event="Guest",
        roles=(),
    ),
    NewContactRow(
        full_name="Marco Mereu",
        first_name="Marco",
        last_name="Mereu",
        email="marco@m80.gg",
        linkedin_url="https://www.linkedin.com/in/marcomereu/",
        accomplishments="Serial gaming and esports entrepreneur who founded five companies and completed three exits\nFounded and sold Roostr to Chartboost in 2016\nFounded and sold Framerate to Super League Gaming in 2019\nFounder and CEO of M80; previously co-founded XSET",
        role_in_event="Guest",
        roles=("CEO", "Founder", "Post-Exit Founder",),
    ),
    NewContactRow(
        full_name="Harry Parmar",
        first_name="Harry",
        last_name="Parmar",
        email="harry@bov.ai",
        linkedin_url="https://www.linkedin.com/in/harry-parmar-44021b208/",
        accomplishments="Founder and Managing Director of Blue Ocean Ventures and BOV.AI\nCEO of No Fear Counselling and Chairman of GuideAI Health\nReal estate developer and strategic partner to high-growth technology companies\nChair of Burnaby Hospital Foundation, supporting a major hospital redevelopment campaign",
        role_in_event="Guest",
        roles=("CEO", "Founder", "Managing Director",),
    ),
    NewContactRow(
        full_name="David Denberg",
        first_name="David",
        last_name="Denberg",
        email="d@daviddenberg.com",
        linkedin_url="https://www.linkedin.com/in/david-denberg-21478225/",
        accomplishments="Partner and longtime Lead Curator at global entrepreneurship community Summit\nHelped scale Summit from a startup into an international events and community platform\nFounded and produced six communities spanning entrepreneurship, sustainability, and social impact\nAdvised 16+ Unreasonable companies and helped shape the Summit Powder Mountain development",
        role_in_event="Guest",
        roles=("Founder",),
    ),
    NewContactRow(
        full_name="Freddy del Barrio",
        first_name="Freddy",
        last_name="del Barrio",
        email="freddy@airhoracare.com",
        linkedin_url="https://www.linkedin.com/in/alfredo-del-barrio-7bb905122/",
        accomplishments="Founder and CEO of Aithora Care, an AI-powered continuous-care platform\nInvestor and operator across technology, hospitality, and private markets\nCo-founded and supported ventures across the U.S. and Europe\nBuilds AI infrastructure for senior living, long-term care, and behavioral health",
        role_in_event="Guest",
        roles=("CEO", "Founder",),
    ),
    NewContactRow(
        full_name="Dalton Little",
        first_name="Dalton",
        last_name="Little",
        email="dlittle@texasenergygroup.com",
        linkedin_url="https://www.linkedin.com/in/dalton-little-030163119/",
        accomplishments="Principal at Prominent Property Group and executive at Texas Energy Group\nReal estate investor and developer active across 13 properties and six holding companies\nLeading a proposed 150-acre data-center development with planned access to 200MW of power",
        role_in_event="Guest",
        roles=(),
    ),
    NewContactRow(
        full_name="Martha Little",
        first_name="Martha",
        last_name="Little",
        email=None,
        linkedin_url="https://www.linkedin.com/in/martha-little-36aab0bb/",
        accomplishments="",
        role_in_event="Guest",
        roles=(),
    ),
    NewContactRow(
        full_name="Hai Nguyen",
        first_name="Hai",
        last_name="Nguyen",
        email="hainguyen99@yahoo.com",
        linkedin_url=None,
        accomplishments="Producer, executive producer, and co-owner of Studio Hill Austin\nGrammy-nominated producer for Mythologies II\nProduced recordings spanning Studio Hill, Abbey Road, Los Angeles, New York, and Buenos Aires\nExecutive producer of the award-winning multimedia project Starlight",
        role_in_event="Guest",
        roles=(),
    ),
    NewContactRow(
        full_name="Robert Gauntt",
        first_name="Robert",
        last_name="Gauntt",
        email="rgauntt@capitalcreek.com",
        linkedin_url="https://www.linkedin.com/in/robert-gauntt-11a1052/",
        accomplishments="Founding Partner and CEO of Capital Creek Partners\nCo-founded Avalon Advisors, which grew into a $9B RIA\nThree decades in investment management, including Goldman Sachs and Morgan Stanley\nUT System Regent and former UTIMCO director and TRS Investment Committee chair",
        role_in_event="Guest",
        roles=("CEO", "Founder", "Founding Partner",),
    ),
    NewContactRow(
        full_name="Ellen Wood",
        first_name="Ellen",
        last_name="Wood",
        email="ewood@vcfo.com",
        linkedin_url="https://www.linkedin.com/in/ellenewood/",
        accomplishments="Co-founder and CEO of vcfo, a pioneer of fractional CFO services\nLed the firm in serving more than 6,000 clients\nNamed to Inc.’s 2025 Female Founders 500\nAustin Tech Hall of Fame inductee and 2024 ABJ CFO Legacy Award recipient",
        role_in_event="Guest",
        roles=("CEO", "CFO", "Founder",),
    ),
    NewContactRow(
        full_name="Matt Lyons",
        first_name="Matt",
        last_name="Lyons",
        email="mlyons@wsgr.com",
        linkedin_url="https://www.linkedin.com/in/mattlyons-techlawyer-austin/",
        accomplishments="Member at Wilson Sonsini Goodrich & Rosati\nFormer Partner at Shearman & Sterling",
        role_in_event="Guest",
        roles=(),
    ),
    NewContactRow(
        full_name="Duffy Oyster",
        first_name="Duffy",
        last_name="Oyster",
        email=None,
        linkedin_url="linkedin.com/in/duffy-oyster-8b9677342",
        accomplishments="Owner of Oyster Landing\nFamily-office principal and private investor",
        role_in_event="Guest",
        roles=("Investor",),
    ),
    NewContactRow(
        full_name="Tal Shmueli",
        first_name="Tal",
        last_name="Shmueli",
        email="ts@texasventurepartners.com",
        linkedin_url="https://www.linkedin.com/in/tshmueli/",
        accomplishments="Tech Investor\nPartner & COO at Texas Venture Partners\nFamily-office principal and private investor",
        role_in_event="Guest",
        roles=("COO", "Investor",),
    ),
    NewContactRow(
        full_name="Andrew Robert Heller",
        first_name="Andrew",
        last_name="Robert Heller",
        email="heller@heller.com",
        linkedin_url="https://www.linkedin.com/in/andrew-heller-500120/",
        accomplishments="Owner at Heller Associates\nFormer President at Heller Aircraft",
        role_in_event="Guest",
        roles=(),
    ),
    NewContactRow(
        full_name="Akshay Bhushan",
        first_name="Akshay",
        last_name="Bhushan",
        email="akshay@tolacapital.com",
        linkedin_url="https://www.linkedin.com/in/akshaybhushan209/",
        accomplishments="Partner at Tola Capital",
        role_in_event="Guest",
        roles=(),
    ),
    NewContactRow(
        full_name="Tom Washmon",
        first_name="Tom",
        last_name="Washmon",
        email="tom@privateercapital.com",
        linkedin_url="https://www.linkedin.com/in/thomas-c-washmon-b175a713/",
        accomplishments="President at Privateer Capital\nFamily-office principal and private investor",
        role_in_event="Guest",
        roles=("Investor",),
    ),
    NewContactRow(
        full_name="Chris Beck",
        first_name="Chris",
        last_name="Beck",
        email="christopher.beck@bswhealth.org",
        linkedin_url="https://www.linkedin.com/in/beckchris/",
        accomplishments="Vice President of Philanthropy at Baylor Scott & White Health\nFormer Senior Director of Development at Dell Children's Medical Center Foundation",
        role_in_event="Guest",
        roles=(),
    ),
    NewContactRow(
        full_name="Valeska Pederson Hintz",
        first_name="Valeska",
        last_name="Pederson Hintz",
        email="valeskap@gmail.com",
        linkedin_url="https://www.linkedin.com/in/valeskapedersonhintz/",
        accomplishments="Partner at Ashurst Perkins Coie, advising technology companies and investors from Series A through IPO\nAdvises on venture financings, M&A, IPOs, secondaries, and governance\nHandled multibillion-dollar transactions involving GoDaddy, eBay, Splunk, and RingCentral",
        role_in_event="Guest",
        roles=(),
    ),
    NewContactRow(
        full_name="Drew Hintz",
        first_name="Drew",
        last_name="Hintz",
        email="hintz@openai.com",
        linkedin_url="https://www.linkedin.com/in/drewhintz/",
        accomplishments="Product Security Lead at OpenAI, securing frontier AI systems\nPreviously directed security operations and product security at Block\nSpent 13+ years in security engineering and leadership at Google\nFormer UT Austin adjunct professor teaching ethical hacking",
        role_in_event="Guest",
        roles=(),
    ),
    NewContactRow(
        full_name="Steve Welch",
        first_name="Steve",
        last_name="Welch",
        email="steve@dreamit.com",
        linkedin_url="https://www.linkedin.com/in/livefreeordie/",
        accomplishments="Founder & Managing Partner at Shark Skin Ventures\nCo-Founder / Board Member at Restore Hyper Wellness\nFounder & Chairman at DreamIt Ventures",
        role_in_event="Guest",
        roles=("Board Member", "Founder", "Managing Partner",),
    ),
    NewContactRow(
        full_name="Firas Sozan",
        first_name="Firas",
        last_name="Sozan",
        email="firas@harrisonclarke.com",
        linkedin_url="https://www.linkedin.com/in/firassozan/",
        accomplishments="Founder & CEO at Harrison Clarke\nFounder & Host at Inside the Silicon Mind\nFounder & CEO at Arke\nFounder & GP at Harrison Clarke Ventures",
        role_in_event="Guest",
        roles=("CEO", "Founder",),
    ),
    NewContactRow(
        full_name="Sally Sozan",
        first_name="Sally",
        last_name="Sozan",
        email="sally@harrisonclarke.com",
        linkedin_url="https://www.linkedin.com/in/sallysozan/",
        accomplishments="Special Projects lead at Harrison Clarke, a search and venture firm focused on Cloud, Data, and AI\nHelped grow the firm from an early-stage startup to offices in four major cities\nSupported early client onboarding, brand development, and engineering-talent sourcing",
        role_in_event="Guest",
        roles=(),
    ),
    NewContactRow(
        full_name="Roger Dickey",
        first_name="Roger",
        last_name="Dickey",
        email="rogeradmin@rocket.st",
        linkedin_url="https://www.linkedin.com/in/rogerdickey/",
        accomplishments="Investor & Advisor at RD Investments\nFounded/sold Gigster to Ionic\nFounded/sold Mafia Wars to Zynga\nFamily-office principal and private investor",
        role_in_event="Guest",
        roles=("Advisor", "Founder", "Investor", "Post-Exit Founder",),
    ),
    NewContactRow(
        full_name="Allison Peck",
        first_name="Allison",
        last_name="Peck",
        email="allison.peck@ext.airbnb.com",
        linkedin_url="https://www.linkedin.com/in/allisonypeck/",
        accomplishments="Regulatory attorney and former counsel at Airbnb and Uber\nAdvised high-growth marketplaces on complex tax, compliance, and public-policy matters\nRepresented Airbnb in municipal negotiations involving lodging taxes and operating rules\nColumbia Law graduate licensed in California and Texas",
        role_in_event="Guest",
        roles=("Lawyer",),
    ),
    NewContactRow(
        full_name="Robyn Johnson",
        first_name="Robyn",
        last_name="Johnson",
        email="robyn@vws.vin",
        linkedin_url="https://www.linkedin.com/in/robyn-johnson-967b48/",
        accomplishments="Co-founder and CEO of Virtuoso Wine & Spirits\nBuilt the family-owned company from its 2003 launch into a statewide Texas distributor\nExpanded operations to climate-controlled warehouses in Austin, Dallas, and Houston\nRepresents independent artisan producers across restaurants, hotels, clubs, and retailers",
        role_in_event="Guest",
        roles=("CEO", "Founder",),
    ),
    NewContactRow(
        full_name="Ethan Drum",
        first_name="Ethan",
        last_name="Drum",
        email="ethandrum@gmail.com",
        linkedin_url="https://www.linkedin.com/in/ethandrum/",
        accomplishments="Founder and CEO at LaaSy\nCo-Founder at LaaSy Health\nBoard Member at Faith Driven Global\n3x exits",
        role_in_event="Guest",
        roles=("Board Member", "CEO", "Founder", "Post-Exit Founder",),
    ),
    NewContactRow(
        full_name="Phil Murray",
        first_name="Phil",
        last_name="Murray",
        email="pmurray@marbellainterests.com",
        linkedin_url="https://www.linkedin.com/in/philmurray1/",
        accomplishments="President at Marbella Interests, LLC\nAdvisor at Reflex\nFormer CEO at milk + honey",
        role_in_event="Guest",
        roles=("Advisor", "CEO",),
    ),
    NewContactRow(
        full_name="Richard Veitenheimer",
        first_name="Richard",
        last_name="Veitenheimer",
        email="rveitenheimer@marbellainterests.com",
        linkedin_url="https://www.linkedin.com/in/richard-veitenheimer-5443585b/",
        accomplishments="#2 at Marbella Interests",
        role_in_event="Guest",
        roles=(),
    ),
    NewContactRow(
        full_name="Sherwin Gandhi",
        first_name="Sherwin",
        last_name="Gandhi",
        email="sherwin.gandhi@gmail.com",
        linkedin_url="https://www.linkedin.com/in/sherwingandhi/",
        accomplishments="Venture Partner at Pioneer Fund\nCo-Founded Jeeves\nPrivate Investor",
        role_in_event="Guest",
        roles=("Founder", "Investor",),
    ),
    NewContactRow(
        full_name="Ankur Agarwal",
        first_name="Ankur",
        last_name="Agarwal",
        email="ankur@evf.vc",
        linkedin_url="https://www.linkedin.com/in/ankuragarwal896/",
        accomplishments="Founder & GP at Executive Venture Fund\nChair/Coach at Vistage Worldwide, Inc.",
        role_in_event="Guest",
        roles=("Founder",),
    ),
    NewContactRow(
        full_name="Rob Neville",
        first_name="Rob",
        last_name="Neville",
        email="rob.neville@gwctx.org",
        linkedin_url="https://www.linkedin.com/in/robertneville/",
        accomplishments="President and CEO at Goodwill Central Texas \nBoard Member at Skope Inc\nManaging Director at Springbok Ventures",
        role_in_event="Guest",
        roles=("Board Member", "CEO", "Managing Director",),
    ),
    NewContactRow(
        full_name="Autumn Manning",
        first_name="Autumn",
        last_name="Manning",
        email="autumn@faanaworks.com",
        linkedin_url="https://www.linkedin.com/in/autumnmanning/",
        accomplishments="Investor Advisor at Funded House\nFormer Mentor at Techstars\nPrivate Investor",
        role_in_event="Guest",
        roles=("Advisor", "Investor",),
    ),
    NewContactRow(
        full_name="Patricia Ponsart",
        first_name="Patricia",
        last_name="Ponsart",
        email=None,
        linkedin_url="https://www.linkedin.com/in/patricia-ponsart-8b62114a/",
        accomplishments="",
        role_in_event="Guest",
        roles=(),
    ),
    NewContactRow(
        full_name="Colin Guinn",
        first_name="Colin",
        last_name="Guinn",
        email="colin@colinguinn.com",
        linkedin_url="https://www.linkedin.com/in/colinguinn/",
        accomplishments="Founder and CEO of Gel Blaster, creator of SURGE\nBuilt it from a 2020 Kickstarter launch into NPD’s fastest-growing U.S. toy company\nFormer founder and CEO of DJI North America\nDrone expert who testified before Congress and advised global technology leaders",
        role_in_event="Guest",
        roles=("CEO", "Founder",),
    ),
    NewContactRow(
        full_name="Michael Malysheva",
        first_name="Michael",
        last_name="Malysheva",
        email=None,
        linkedin_url="https://www.linkedin.com/in/michael-malyshev-916143239/",
        accomplishments="Oksana son",
        role_in_event="Guest",
        roles=(),
    ),
    NewContactRow(
        full_name="Eugene Sosnovsky",
        first_name="Eugene",
        last_name="Sosnovsky",
        email="esosnovsky1@gmail.com",
        linkedin_url="https://www.linkedin.com/in/eugene-sosnovsky-%F0%9F%93%AC-8744b7392/",
        accomplishments="3x exits\nCo-Founder/CEO at PostScout\nCo-Founder/CEO at Mad Lemon Media",
        role_in_event="Guest",
        roles=("CEO", "Founder", "Post-Exit Founder",),
    ),
    NewContactRow(
        full_name="Aaron Batalion",
        first_name="Aaron",
        last_name="Batalion",
        email="aaronbatalion@gmail.com",
        linkedin_url="https://www.linkedin.com/in/aaronbatalion/",
        accomplishments="Co-founded LivingSocial and served as its first CTO\nScaled the marketplace to nearly 70M members and a reported $6B peak valuation\nFormer partner at Lightspeed Venture Partners\nAngel investor and advisor to 40+ consumer and enterprise technology companies",
        role_in_event="Guest",
        roles=("Advisor", "CTO", "Founder", "Investor",),
    ),
    NewContactRow(
        full_name="John Melvin",
        first_name="John",
        last_name="Melvin",
        email="john@swellspirits.com",
        linkedin_url="https://www.linkedin.com/in/johnlmelvin/",
        accomplishments="Founder of Swell Spirits and co-founder of Goodjuice and Montagave Tequila\nBuilt Montagave around tequila rested in Grand Cru Bordeaux wine barrels\nProduces curated wine-and-spirits events and education through Goodjuice\nFormer Vice President at energy-risk advisory firm Mobius Risk Group",
        role_in_event="Guest",
        roles=("Founder",),
    ),
    NewContactRow(
        full_name="Rafael Martinez",
        first_name="Rafael",
        last_name="Martinez",
        email="rafael@maximocapital.com",
        linkedin_url="https://www.linkedin.com/in/rafamartinez812/",
        accomplishments="Founder and Principal of Maximo Capital, his privately funded family office\nFounder and CEO of RAFA Family of Companies, an integrated motorsports platform reaching 40M+ monthly views\nPartner and West Desk Head at Hartree Partners, with two decades in global commodities and capital markets",
        role_in_event="Guest",
        roles=("CEO", "Founder",),
    ),
    NewContactRow(
        full_name="Jeff Serra",
        first_name="Jeff",
        last_name="Serra",
        email="jeffrserra@gmail.com",
        linkedin_url="https://www.linkedin.com/in/jeff-serra-5a91b61/",
        accomplishments="Former CEO and co-founder of Vida Capital, an alternative asset manager acquired by RedBird Capital and Reverence Capital Partners\nFounded Re-NEW Energy, sold to Sempra Energy and Progress Energy for $100M+ tied to fuel output\nFormer Chairman, President and CEO of Phibro Energy\n2011 RISE Austin Serial Entrepreneur of the Year",
        role_in_event="Guest",
        roles=("CEO", "Founder", "Post-Exit Founder",),
    ),
    NewContactRow(
        full_name="Darsh Singh",
        first_name="Darsh",
        last_name="Singh",
        email="darsh@hazoorpartners.com",
        linkedin_url="https://www.linkedin.com/in/darsh-singh-4927998/",
        accomplishments="Co-founder, CIO, and Managing Partner of Hazoor Partners\nLeads research and portfolio management across digital assets and niche alternative investments\nFormer Satori Capital portfolio manager and NSA signals-intelligence engineer\nServes on Trinity University’s Board of Trustees and JUST’s board\nFamily-office principal and private investor",
        role_in_event="Guest",
        roles=("CIO", "Founder", "Investor", "Managing Partner",),
    ),
    NewContactRow(
        full_name="Erin Taylor",
        first_name="Erin",
        last_name="Taylor",
        email="erin@hazoorpartners.com",
        linkedin_url="https://www.linkedin.com/in/edt818/",
        accomplishments="Chief Experience Officer at Hazoor Partners, an alternative-investment manager\nOversees relationships with investors, service providers, and the firm’s team\nSupports clients spanning individuals, family offices, wealth managers, and institutions\nFormer Able Lending Chief of Staff, managing team and operations",
        role_in_event="Guest",
        roles=(),
    ),
    NewContactRow(
        full_name="Felisha McDouglad",
        first_name="Felisha",
        last_name="McDouglad",
        email="fe@mwpins.com",
        linkedin_url="https://www.linkedin.com/in/felisha-anna-mason-mcdougald-18b8479/",
        accomplishments="Owner and Risk Advisor at Midwest Professional Insurance\nBrings 17+ years across commercial, personal, aviation, and management-liability risk\nCertified Insurance Counselor, Personal Risk Manager, and Management Liability Insurance Specialist\nTeaches aviation risk transference; former hotel owner and real-estate developer",
        role_in_event="Guest",
        roles=("Advisor",),
    ),
    NewContactRow(
        full_name="Melissa Goertz",
        first_name="Melissa",
        last_name="Goertz",
        email="melissa@montegoertzco.com",
        linkedin_url="linkedin.com/in/melissa-goertz-00bab0394",
        accomplishments="Small-business owner at Monte Goertz Company LLC\nHelps operate an Austin-based, privately held family business active since 2013",
        role_in_event="Guest",
        roles=(),
    ),
    NewContactRow(
        full_name="James Chrichton",
        first_name="James",
        last_name="Chrichton",
        email="james.crichton@gmail.com",
        linkedin_url="https://www.linkedin.com/in/james-crichton-b484011a/",
        accomplishments="Founder & CEO of Arthur Analytics, an AI-driven art-market intelligence platform\nCo-founded Scout Capital Management, which managed approximately $6B in assets\nFounded and led Hitchwood Capital Management, a long/short investment firm\nWest Point graduate and Harvard Business School MBA",
        role_in_event="Guest",
        roles=("CEO", "Founder",),
    ),
    NewContactRow(
        full_name="Nilo Chrichton",
        first_name="Nilo",
        last_name="Chrichton",
        email="niazi@nextherapy.ch",
        linkedin_url="https://www.linkedin.com/in/nilofar-niazi/",
        accomplishments="CEO at Nextherapy\nFounder at TRAINM\nBoard Member at Neural Stem Cell Institute",
        role_in_event="Guest",
        roles=("Board Member", "CEO", "Founder",),
    ),
    NewContactRow(
        full_name="Julien Khaleghy",
        first_name="Julien",
        last_name="Khaleghy",
        email="julien@serpapi.com",
        linkedin_url="https://www.linkedin.com/in/julienkhaleghy",
        accomplishments="Founder and CEO of SerpApi\nBuilt one of the first APIs providing structured, real-time search-engine data\nScaled SerpApi to more than 1.5 million activated accounts\nServes organizations including Nvidia, Adobe, and the United Nations",
        role_in_event="Guest",
        roles=("CEO", "Founder",),
    ),
    NewContactRow(
        full_name="Adrianna DeLorenzo",
        first_name="Adrianna",
        last_name="DeLorenzo",
        email="adrianna_delorenzo@yahoo.com",
        linkedin_url="https://www.linkedin.com/in/adridelo/",
        accomplishments="Former VP of Services and Support at Jirav\nLed its professional services, customer support, and education teams\nBrings 10+ years of experience across FP&A software and consulting\nHelped hundreds of companies improve forecasting and business decisions",
        role_in_event="Guest",
        roles=(),
    ),
    NewContactRow(
        full_name="James Gauthreaux",
        first_name="James",
        last_name="Gauthreaux",
        email=None,
        linkedin_url="https://www.linkedin.com/in/james-gauthreaux-98a35b198/",
        accomplishments="Founder at Mr Maison Home Concierge\nFamily-office principal and private investor",
        role_in_event="Guest",
        roles=("Founder", "Investor",),
    ),
    NewContactRow(
        full_name="Travis Bales",
        first_name="Travis",
        last_name="Bales",
        email="t_bales@icloud.com",
        linkedin_url="https://www.linkedin.com/in/tbales/",
        accomplishments="Managing Director of Booz Allen Ventures\nLeads early-stage investments across defense, AI, cybersecurity, space, deep tech, and reindustrialization\nHelped build a portfolio including Hidden Level, Shift5, Albedo, Credo AI, and Second Front\nFormer U.S. Army officer focused on bringing dual-use technology into critical government missions",
        role_in_event="Guest",
        roles=("Investor", "Managing Director",),
    ),
    NewContactRow(
        full_name="Cassandra Krcmar",
        first_name="Cassandra",
        last_name="Krcmar",
        email="cassandra@itshandledconsulting.com",
        linkedin_url="https://www.linkedin.com/in/cassandrakrcmarms/",
        accomplishments="Founder of It’s Handled Consulting, serving ultra-high-net-worth individuals and family offices since 2013\nProvides family-office advising, executive support, recruiting, and luxury lifestyle management\nFounder of CYR Coaching, focused on communication, relationships, and growth\nFormer volunteer with anti-trafficking and prison-education organizations",
        role_in_event="Guest",
        roles=("Founder",),
    ),
    NewContactRow(
        full_name="Kevin Lippy",
        first_name="Kevin",
        last_name="Lippy",
        email="kevinlippy@gmail.com",
        linkedin_url="https://www.linkedin.com/in/kevin-lippy-92598717/",
        accomplishments="Co-founder and COO of reMKTR, an automated Amazon DSP management platform\nBuilds advertising technology using Amazon Marketing Cloud and real-time campaign optimization\nMember of Million Dollar Sellers with experience scaling Amazon businesses\nPreviously co-founded and led 28th Labs as CEO",
        role_in_event="Guest",
        roles=("CEO", "COO", "Founder",),
    ),
    NewContactRow(
        full_name="Kim Lippy",
        first_name="Kim",
        last_name="Lippy",
        email=None,
        linkedin_url="https://www.linkedin.com/in/kim-lippy/",
        accomplishments="Founder of consumer-products venture THE POTTYS\nExperienced business manager with a background in sales and team leadership\nUniversity of Technology Sydney graduate",
        role_in_event="Guest",
        roles=("Founder",),
    ),
    NewContactRow(
        full_name="Rob Provine",
        first_name="Rob",
        last_name="Provine",
        email="robert@timberlinerep.com",
        linkedin_url="https://www.linkedin.com/in/robert-p-b32a2247/",
        accomplishments="Partner and COO at Timberline Real Estate Partners\nFormer partner and Investment Committee member at $6B Meyer Bergman\nPreviously Managing Director at Somerston Capital, a $1.5B family office\nCo-founded and sold a development platform that delivered 2M+ square feet",
        role_in_event="Guest",
        roles=("COO", "Founder", "Managing Director", "Post-Exit Founder",),
    ),
    NewContactRow(
        full_name="Elena Provine",
        first_name="Elena",
        last_name="Provine",
        email="elenaprovine@gmail.com",
        linkedin_url="https://www.linkedin.com/in/elenaprovine/",
        accomplishments="Investor Relations Manager at BITKRAFT Ventures, focused on long-term investor partnerships\nFormerly led U.S. gaming partnerships at blockchain gaming platform Immutable\nFormer Venture Partner at Griffin Gaming Partners\nShareholder at Timberline Real Estate Partners; previously supported Skillz’s public-market debut",
        role_in_event="Guest",
        roles=(),
    ),
    NewContactRow(
        full_name="Darcy Harbott",
        first_name="Darcy",
        last_name="Harbott",
        email="darcy@harbocapital.com",
        linkedin_url="https://www.linkedin.com/in/darcy-harbott-76089418/",
        accomplishments="Sponsor and GP of BlackGold Wealth, an oil-and-gas working-interest fund\nFounded more than 18 companies and holds three patents\nCompleted an eight-figure company exit\nFour decades in entrepreneurship, operations, franchising, tax strategy, and alternative investing",
        role_in_event="Guest",
        roles=("Founder",),
    ),
    NewContactRow(
        full_name="Anya Tomkies",
        first_name="Anya",
        last_name="Tomkies",
        email=None,
        linkedin_url="https://www.linkedin.com/in/annatomkies/",
        accomplishments="Board-certified otolaryngologist at Austin ENT Clinic\nAlpha Omega Alpha honoree and co-author of peer-reviewed pediatric sleep research\nFounded UTSW Healthy Living to teach youth about preventive health",
        role_in_event="Guest",
        roles=("Doctor", "Founder",),
    ),
    NewContactRow(
        full_name="Brian Sanders",
        first_name="Brian",
        last_name="Sanders",
        email="brian@sapien.org",
        linkedin_url="https://www.linkedin.com/in/briancsanders/",
        accomplishments="Founder of Sapien and the Sapien Center, an Austin health and social club\nBuilt animal-based nutrition and body-care company Nose to Tail\nCreator of the Food Lies documentary series\nHost of the Peak Human nutrition podcast",
        role_in_event="Guest",
        roles=("Founder",),
    ),
    NewContactRow(
        full_name="Robyn Siers",
        first_name="Robyn",
        last_name="Siers",
        email="robyn.siers@jonesspross.com",
        linkedin_url="https://www.linkedin.com/in/robynsiers/",
        accomplishments="Partner and M&A Practice Leader at JonesSpross\nCo-created Speed M&A, using technology and playbooks to streamline transactions\nRepresents strategic and financial buyers and sellers across 100+ transactions annually\nFormer Cooley corporate attorney and advocate expanding M&A access for women founders",
        role_in_event="Guest",
        roles=("Lawyer",),
    ),
    NewContactRow(
        full_name="Bret Siers",
        first_name="Bret",
        last_name="Siers",
        email="bsiers@adoptsequence.com",
        linkedin_url="https://www.linkedin.com/in/bret-siers/",
        accomplishments="Co-founder and CEO of AI video platform Sequence\nFounder and CEO of SiteWarming, a platform for activating dormant domains\nSpent 25 years building businesses in financial services\nPreviously built and sold a company before moving into technology",
        role_in_event="Guest",
        roles=("CEO", "Founder",),
    ),
    NewContactRow(
        full_name="Sabrina Mallick",
        first_name="Sabrina",
        last_name="Mallick",
        email="s.mallick@mallickch.com",
        linkedin_url="https://www.linkedin.com/in/smallick/",
        accomplishments="Founder of Sunset Ventures, a consumer and retail investment firm\nBacked SmartyPants and Knix before their acquisitions by Unilever and Essity\nCo-founded Pure Growth Organic, achieving nationwide Walmart distribution\nBoard member at Hill House Home and Princess House",
        role_in_event="Guest",
        roles=("Board Member", "Founder",),
    ),
    NewContactRow(
        full_name="Brendan McCord",
        first_name="Brendan",
        last_name="McCord",
        email="m.brendan.mccord@gmail.com",
        linkedin_url="https://www.linkedin.com/in/brendan-mccord/",
        accomplishments="Founder and Chair of Cosmos Institute\nFounded two AI startups acquired for a combined $400M\nFounded the DoD’s first applied AI organization and authored its first AI strategy\nFormer submarine officer who spent 610 days underwater",
        role_in_event="Guest",
        roles=("Founder", "Post-Exit Founder",),
    ),
    NewContactRow(
        full_name="Adrienne McCord",
        first_name="Adrienne",
        last_name="McCord",
        email=None,
        linkedin_url="https://www.linkedin.com/in/adriane-mccord/",
        accomplishments="Co-founder and board member of Cosmos Institute\nPsychotherapist and executive coach serving high-achieving leaders\nFormer strategy and operations leader at LinkedIn, Workrise, and Deloitte\nHarvard MBA with a Northwestern master’s in clinical mental health counseling",
        role_in_event="Guest",
        roles=("Board Member", "Founder",),
    ),
    NewContactRow(
        full_name="Brad Weimert",
        first_name="Brad",
        last_name="Weimert",
        email="brad@epd.com",
        linkedin_url="https://www.linkedin.com/in/bradweimert",
        accomplishments="Founder at Easy Pay Direct\nHost at Beyond A Million podcast\nFamily-office principal and private investor",
        role_in_event="Guest",
        roles=("Founder", "Investor",),
    ),
    NewContactRow(
        full_name="Hudson Thomas",
        first_name="Hudson",
        last_name="Thomas",
        email="hudson@transforminvest.com",
        linkedin_url="https://www.linkedin.com/in/hudsontthomas/",
        accomplishments="",
        role_in_event="Guest",
        roles=(),
    ),
    NewContactRow(
        full_name="Rod Williams",
        first_name="Rod",
        last_name="Williams",
        email="rod@corporatelodging.com",
        linkedin_url="https://www.linkedin.com/in/rodwilliamsleadership",
        accomplishments="",
        role_in_event="Guest",
        roles=(),
    ),
    NewContactRow(
        full_name="Will Overlander",
        first_name="Will",
        last_name="Overlander",
        email=None,
        linkedin_url="https://www.linkedin.com/in/will-overlander-40698667/",
        accomplishments="TriNet",
        role_in_event="Sponsors",
        roles=(),
    ),
    NewContactRow(
        full_name="Cody Arnold",
        first_name="Cody",
        last_name="Arnold",
        email="cody.arnold@trinet.com",
        linkedin_url="https://www.linkedin.com/in/cody-arnold-a824081a/",
        accomplishments="TriNet",
        role_in_event="Sponsors",
        roles=(),
    ),
    NewContactRow(
        full_name="Gianina Reibling",
        first_name="Gianina",
        last_name="Reibling",
        email="greibling.ic@soulidaritytherapy.com",
        linkedin_url="https://www.linkedin.com/in/gianina-casareno-reibling-6b7348233/",
        accomplishments="Techsyn Ventures",
        role_in_event="Sponsors",
        roles=(),
    ),
    NewContactRow(
        full_name="Stephen Feinstein",
        first_name="Stephen",
        last_name="Feinstein",
        email="stephen.feinstein@jpmorgan.com",
        linkedin_url="https://www.linkedin.com/in/stephen-feinstein/",
        accomplishments="JPMorgan",
        role_in_event="Sponsors",
        roles=(),
    ),
    NewContactRow(
        full_name="Jeff Forbes",
        first_name="Jeff",
        last_name="Forbes",
        email="jeff.forbes@jpmorgan.com",
        linkedin_url="https://www.linkedin.com/in/jeffreymforbes/",
        accomplishments="JPMorgan",
        role_in_event="Sponsors",
        roles=(),
    ),
    NewContactRow(
        full_name="Ashley Bruckneur",
        first_name="Ashley",
        last_name="Bruckneur",
        email="ashley.brueckner@jpmorgan.com",
        linkedin_url="https://www.linkedin.com/in/ashley-brueckner-cfa-2295635/",
        accomplishments="JPMorgan",
        role_in_event="Sponsors",
        roles=(),
    ),
    NewContactRow(
        full_name="Andrew Kennedy",
        first_name="Andrew",
        last_name="Kennedy",
        email="andrew.j.kennedy@jpmorgan.com",
        linkedin_url="https://www.linkedin.com/in/andrew-kennedy-a9891a82/",
        accomplishments="JPMorgan",
        role_in_event="Sponsors",
        roles=(),
    ),
    NewContactRow(
        full_name="Kevin Crabb",
        first_name="Kevin",
        last_name="Crabb",
        email="kevin.crabb@jpmorgan.com",
        linkedin_url="https://www.linkedin.com/in/kevin-crabb-a48298111/",
        accomplishments="JPMorgan",
        role_in_event="Sponsors",
        roles=(),
    ),
    NewContactRow(
        full_name="Amy Miller",
        first_name="Amy",
        last_name="Miller",
        email="amiller6@alliant.com",
        linkedin_url="https://www.linkedin.com/in/amy-miller1/",
        accomplishments="Alliant",
        role_in_event="Sponsors",
        roles=(),
    ),
    NewContactRow(
        full_name="Crystal Calvo",
        first_name="Crystal",
        last_name="Calvo",
        email="crystal.calvo@alliant.com",
        linkedin_url="https://www.linkedin.com/in/calvocrystal/",
        accomplishments="Alliant",
        role_in_event="Sponsors",
        roles=(),
    ),
)

# Structural constants a caller/test can assert against without recounting the tuples above.
EXISTING_CONTACTS_SIZE = 55
NEW_CONTACTS_SIZE = 111
TOTAL_COHORT_SIZE = 166

NAME_ONLY_CANDIDATES_EXCLUDED = 4
INSUFFICIENT_IDENTITY_EXCLUDED = 17
CSV_DUPLICATE_COLLAPSED = 1
CSV_TOTAL_ROWS = 188

DINNER_ATTENDED_VALUE = "Austin Forward - 09.10.2026 - Austin"
DINNER_SUBSCRIPTION_VALUE = "Fireside Dinners"
TARGET_LIST_ID = "11d9dcdf-bae2-452d-a425-d2035e27aedd"
TARGET_LIST_NAME = "Austin Forward - 09.10.2026 - Austin"
TARGET_LOCATION = {"city": "Austin", "state": "Texas", "country": "United States"}
PROVENANCE_SOURCE = "austin_forward_guest_list_2026_09_10"
NOTES_HEADER = "Austin Forward guest bio:"
POST_EXIT_FOUNDER_ROLE = "Post-Exit Founder"
